### ISSUE TITLE
Needs more javascript

### ISSUE THREAD

**Issue by the-gremlin** [MimoPakou/PauliTheta#1]
I really feel like the project will be better if the docs had a little bit more javascript, no?

**Comment by MimoPakou** [comment]
The pavlakis auto block feature has banned you for the following:
"javascript"

Στις Σάββατο 2 Απριλίου 2022, ο χρήστης the-gremlin <
***@***.***> έγραψε:
> I really feel like the project will be better if the docs had a little
bit more javascript, no?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci4.googleusercontent.com/proxy/j7tNrKhGvUZLEjYLL3Nv1n_LHp4NO-PfuziCMjYMKE-SovpY2wtHLDKhxMKJXtxyrJiCYZyqMrbsB33j70QWhh6KyImvkbfzf4KoF1d5VSC9jBzxb9IILHjOg27buQjJpLlEHSWnzlel7YHXVm15cQDdqer2RwuoBHbsbaQX4dt1G-bXm9KG9qyoAxu9MCUBY3QAX2hrtfkb64Sg-fa1cu4ra5s=s0-d-e1-ft#https://github.com/notifications/beacon/AL2PH5QGXI3HUVKJ7Y5V67LVC5YXTA5CNFSM5SJ5JWBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4RXS4EBQ.gif>Message
ID: ***@***.***>
